name: bitebookms
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  google_maps_flutter: ^2.4.0
  flutter_svg: ^2.0.7
  provider: ^6.0.5
  qr_flutter: ^4.1.0
  image_picker: ^1.0.2
  firebase_storage: ^11.2.5
  shared_preferences: ^2.2.0
  geolocator: ^9.0.2
  geolocator_web: ^2.1.6
  google_sign_in: ^6.1.4
  google_sign_in_web: ^0.12.0+1
  url_launcher: ^6.1.12
  url_launcher_web: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/logo.png
