# Podfile for BiteBookMS iOS Project

platform :ios, '11.0'

# CocoaPods analytics
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Get the Flutter root directory
flutter_root = File.expand_path('..', Dir.pwd)

# Load the default iOS Flutter setup
load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  # Flutter setup
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))

  # Firebase pods
  pod 'Firebase/Core' # Required for Firebase Core
  pod 'Firebase/Auth' # Authentication
  pod 'Firebase/Firestore' # Firestore database
  pod 'Firebase/Storage' # Firebase Storage
  pod 'Firebase/Messaging' # Firebase Cloud Messaging
  pod 'Firebase/Analytics' # Analytics
  pod 'Firebase/RemoteConfig' # Remote Config

  # Additional dependencies, if needed
  # Add any other dependencies for the project here
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    # Enable bitcode if you need it
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
